### ISSUE TITLE
publishing to Ubuntu Touch

### ISSUE THREAD

**Issue by lduboeuf** [zccrs/Aircraft-War#2]
Hello,

I would like to deploy your app to Ubuntu Touch but don't know what Licence is your project ?
Do you allow me to publish it to the store ?
regards

**Comment by AfterTheRainOfStars** [comment]
Hi, Don't be worry, I will change license to MIT for it. good luck!------------------ 原始邮件 ------------------
发件人: "Lionel Duboeuf"<notifications@github.com>
发送时间: 2019年6月11日(星期二) 晚上8:48
收件人: "zccrs/Aircraft-War"<Aircraft-War@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [zccrs/Aircraft-War] publishing to Ubuntu Touch (#2)



Hello,
 
I would like to deploy your app to Ubuntu Touch but don't know what Licence is your project ?
 Do you allow me to publish it to the store ?
 regards
 
&mdash;

**Comment by lduboeuf** [comment]
hi, i saw your reply but it is deleted since then. Anything wrong ? I've successfully deploy your app on my device, of course i need to remove the scoring feature, backend is not available anymore.
Waiting for your response.
Cheers

**Comment by zccrs** [comment]
> hi, i saw your reply but it is deleted since then. Anything wrong ? I've successfully deploy your app on my device, of course i need to remove the scoring feature, backend is not available anymore.
> Waiting for your response.
> Cheers

The reply was created by the mail, but its content was too messy, so I deleted it and will to reply with github, but later forgot, sorry.

This project can be used at anything, I will add a license file for it when I have time.

**Comment by lduboeuf** [comment]
thanks, your app is published on OpenStore, you can see here: https://open-store.io/app/me.lduboeuf.aircraftwar
if you see things that need to be added/modified, just let me know.
